import 'package:flutter/material.dart';

enum GameDemoPhase { countdown, pattern, input, failure, levelUp, victory }

enum GameDemoTapResult { correct, wrong }

class GameDemoTile {
  const GameDemoTile({
    required this.color,
    required this.glow,
    required this.label,
  });

  final Color color;
  final Color glow;
  final String label;
}

class GameDemoStep {
  const GameDemoStep({
    required this.duration,
    required this.phase,
    required this.round,
    required this.level,
    required this.pattern,
    required this.yourProgress,
    required this.opponentOneProgress,
    required this.opponentTwoProgress,
    this.countdownValue,
    this.litTileIndex,
    this.tapPosition,
    this.tapResult,
    this.errorTileIndex,
    this.isLeading = false,
  });

  final Duration duration;
  final GameDemoPhase phase;
  final int round;
  final int level;
  final List<int> pattern;
  final int yourProgress;
  final int opponentOneProgress;
  final int opponentTwoProgress;
  final int? countdownValue;
  final int? litTileIndex;
  final int? tapPosition;
  final GameDemoTapResult? tapResult;
  final int? errorTileIndex;
  final bool isLeading;
}

const List<int> gameDemoRoundOnePattern = <int>[1, 3, 0, 2];
const List<int> gameDemoRoundTwoPattern = <int>[0, 1, 3, 2, 0];

GameDemoStep _step({
  required int ms,
  required GameDemoPhase phase,
  required int round,
  required int level,
  required List<int> pattern,
  required int yourProgress,
  required int opponentOneProgress,
  required int opponentTwoProgress,
  int? countdownValue,
  int? litTileIndex,
  int? tapPosition,
  GameDemoTapResult? tapResult,
  int? errorTileIndex,
  bool isLeading = false,
}) {
  return GameDemoStep(
    duration: Duration(milliseconds: ms),
    phase: phase,
    round: round,
    level: level,
    pattern: pattern,
    yourProgress: yourProgress,
    opponentOneProgress: opponentOneProgress,
    opponentTwoProgress: opponentTwoProgress,
    countdownValue: countdownValue,
    litTileIndex: litTileIndex,
    tapPosition: tapPosition,
    tapResult: tapResult,
    errorTileIndex: errorTileIndex,
    isLeading: isLeading,
  );
}

abstract final class GameDemoSequence {
  static const List<GameDemoTile> tiles = <GameDemoTile>[
    GameDemoTile(
      color: Color(0xFFEF4444),
      glow: Color(0xAAEF4444),
      label: 'RED',
    ),
    GameDemoTile(
      color: Color(0xFF3B82F6),
      glow: Color(0xAA3B82F6),
      label: 'BLUE',
    ),
    GameDemoTile(
      color: Color(0xFF22C55E),
      glow: Color(0xAA22C55E),
      label: 'GREEN',
    ),
    GameDemoTile(
      color: Color(0xFFF59E0B),
      glow: Color(0xAAF59E0B),
      label: 'YELLOW',
    ),
  ];

  static const List<String> opponents = <String>['NightOwl', 'FastFin'];

  // Temporary UI-only sequence until backend match state is integrated.
  static final List<GameDemoStep> steps = <GameDemoStep>[
    _step(
      ms: 850,
      phase: GameDemoPhase.countdown,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      countdownValue: 3,
      yourProgress: 60,
      opponentOneProgress: 42,
      opponentTwoProgress: 26,
    ),
    _step(
      ms: 850,
      phase: GameDemoPhase.countdown,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      countdownValue: 2,
      yourProgress: 60,
      opponentOneProgress: 42,
      opponentTwoProgress: 26,
    ),
    _step(
      ms: 850,
      phase: GameDemoPhase.countdown,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      countdownValue: 1,
      yourProgress: 60,
      opponentOneProgress: 42,
      opponentTwoProgress: 26,
    ),
    _step(
      ms: 900,
      phase: GameDemoPhase.countdown,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      countdownValue: 0,
      yourProgress: 60,
      opponentOneProgress: 42,
      opponentTwoProgress: 26,
    ),
    _step(
      ms: 650,
      phase: GameDemoPhase.pattern,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      litTileIndex: 1,
      yourProgress: 60,
      opponentOneProgress: 45,
      opponentTwoProgress: 28,
    ),
    _step(
      ms: 650,
      phase: GameDemoPhase.pattern,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      litTileIndex: 3,
      yourProgress: 60,
      opponentOneProgress: 46,
      opponentTwoProgress: 29,
    ),
    _step(
      ms: 650,
      phase: GameDemoPhase.pattern,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      litTileIndex: 0,
      yourProgress: 60,
      opponentOneProgress: 47,
      opponentTwoProgress: 30,
    ),
    _step(
      ms: 650,
      phase: GameDemoPhase.pattern,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      litTileIndex: 2,
      yourProgress: 60,
      opponentOneProgress: 48,
      opponentTwoProgress: 31,
    ),
    _step(
      ms: 300,
      phase: GameDemoPhase.pattern,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      yourProgress: 60,
      opponentOneProgress: 49,
      opponentTwoProgress: 32,
    ),
    _step(
      ms: 520,
      phase: GameDemoPhase.input,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      tapPosition: -1,
      yourProgress: 60,
      opponentOneProgress: 50,
      opponentTwoProgress: 33,
    ),
    _step(
      ms: 420,
      phase: GameDemoPhase.input,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      tapPosition: 0,
      tapResult: GameDemoTapResult.correct,
      yourProgress: 62,
      opponentOneProgress: 51,
      opponentTwoProgress: 34,
    ),
    _step(
      ms: 420,
      phase: GameDemoPhase.input,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      tapPosition: 1,
      tapResult: GameDemoTapResult.correct,
      yourProgress: 64,
      opponentOneProgress: 52,
      opponentTwoProgress: 34,
    ),
    _step(
      ms: 420,
      phase: GameDemoPhase.input,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      tapPosition: 2,
      tapResult: GameDemoTapResult.wrong,
      errorTileIndex: 2,
      yourProgress: 64,
      opponentOneProgress: 53,
      opponentTwoProgress: 35,
    ),
    _step(
      ms: 3200,
      phase: GameDemoPhase.failure,
      round: 1,
      level: 5,
      pattern: gameDemoRoundOnePattern,
      tapPosition: 2,
      errorTileIndex: 2,
      yourProgress: 60,
      opponentOneProgress: 55,
      opponentTwoProgress: 36,
    ),
    _step(
      ms: 500,
      phase: GameDemoPhase.countdown,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      countdownValue: 3,
      yourProgress: 60,
      opponentOneProgress: 56,
      opponentTwoProgress: 37,
    ),
    _step(
      ms: 500,
      phase: GameDemoPhase.countdown,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      countdownValue: 2,
      yourProgress: 60,
      opponentOneProgress: 57,
      opponentTwoProgress: 38,
    ),
    _step(
      ms: 500,
      phase: GameDemoPhase.countdown,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      countdownValue: 1,
      yourProgress: 60,
      opponentOneProgress: 57,
      opponentTwoProgress: 38,
    ),
    _step(
      ms: 700,
      phase: GameDemoPhase.countdown,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      countdownValue: 0,
      yourProgress: 60,
      opponentOneProgress: 58,
      opponentTwoProgress: 39,
    ),
    _step(
      ms: 600,
      phase: GameDemoPhase.pattern,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      litTileIndex: 0,
      yourProgress: 60,
      opponentOneProgress: 59,
      opponentTwoProgress: 40,
    ),
    _step(
      ms: 600,
      phase: GameDemoPhase.pattern,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      litTileIndex: 1,
      yourProgress: 60,
      opponentOneProgress: 60,
      opponentTwoProgress: 40,
    ),
    _step(
      ms: 600,
      phase: GameDemoPhase.pattern,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      litTileIndex: 3,
      yourProgress: 60,
      opponentOneProgress: 61,
      opponentTwoProgress: 41,
    ),
    _step(
      ms: 600,
      phase: GameDemoPhase.pattern,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      litTileIndex: 2,
      yourProgress: 60,
      opponentOneProgress: 62,
      opponentTwoProgress: 41,
    ),
    _step(
      ms: 600,
      phase: GameDemoPhase.pattern,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      litTileIndex: 0,
      yourProgress: 60,
      opponentOneProgress: 63,
      opponentTwoProgress: 42,
    ),
    _step(
      ms: 350,
      phase: GameDemoPhase.pattern,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      yourProgress: 60,
      opponentOneProgress: 64,
      opponentTwoProgress: 42,
    ),
    _step(
      ms: 480,
      phase: GameDemoPhase.input,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      tapPosition: -1,
      isLeading: true,
      yourProgress: 60,
      opponentOneProgress: 65,
      opponentTwoProgress: 43,
    ),
    _step(
      ms: 380,
      phase: GameDemoPhase.input,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      tapPosition: 0,
      tapResult: GameDemoTapResult.correct,
      isLeading: true,
      yourProgress: 62,
      opponentOneProgress: 66,
      opponentTwoProgress: 43,
    ),
    _step(
      ms: 380,
      phase: GameDemoPhase.input,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      tapPosition: 1,
      tapResult: GameDemoTapResult.correct,
      isLeading: true,
      yourProgress: 64,
      opponentOneProgress: 67,
      opponentTwoProgress: 44,
    ),
    _step(
      ms: 380,
      phase: GameDemoPhase.input,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      tapPosition: 2,
      tapResult: GameDemoTapResult.correct,
      isLeading: true,
      yourProgress: 66,
      opponentOneProgress: 68,
      opponentTwoProgress: 44,
    ),
    _step(
      ms: 380,
      phase: GameDemoPhase.input,
      round: 2,
      level: 5,
      pattern: gameDemoRoundTwoPattern,
      tapPosition: 3,
      tapResult: GameDemoTapResult.correct,
      isLeading: true,
      yourProgress: 70,
      opponentOneProgress: 71,
      opponentTwoProgress: 46,
    ),
    _step(
      ms: 2600,
      phase: GameDemoPhase.levelUp,
      round: 2,
      level: 6,
      pattern: gameDemoRoundTwoPattern,
      isLeading: true,
      yourProgress: 78,
      opponentOneProgress: 72,
      opponentTwoProgress: 48,
    ),
    _step(
      ms: 4000,
      phase: GameDemoPhase.victory,
      round: 2,
      level: 6,
      pattern: gameDemoRoundTwoPattern,
      yourProgress: 85,
      opponentOneProgress: 74,
      opponentTwoProgress: 50,
    ),
  ];
}
